# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8563304264c823c6beaf8988d81f9ace5be80d492f41eaac5f80e15ff979b0a2b509525fb58f8c0d839a6fd6d3668371f9821d67e7c7f1af1c422fa1bb3adb2d

test:
  secret_key_base: a4a8819b5478c9a3443c0fe63f52a9e5f00cc6f02c9cc4e7de94bbb036163604a5a901322073c3977d5b92359044f5ac90baaf08481041eb893a7d06911fe698

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
